# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: mongodatabase
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongoexpress
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
